//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFloristNewApp18.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int admin_id { get; set; }
        public string ad_email { get; set; }
        public string ad_firstname { get; set; }
        public string ad_lastname { get; set; }
        public string ad_cell { get; set; }
        public string ad_password { get; set; }
    }
}
