//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFloristNewApp18.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int d_id { get; set; }
        public string d_email { get; set; }
        public string d_firstname { get; set; }
        public string d_lastname { get; set; }
        public string d_cell { get; set; }
        public string d_password { get; set; }
        public Nullable<int> ord_id { get; set; }
    
        public virtual Orderr Orderr { get; set; }
    }
}
