//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFloristNewApp18.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NetFloristNewApp18dbEntities2 : DbContext
    {
        public NetFloristNewApp18dbEntities2()
            : base("name=NetFloristNewApp18dbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Ord_Tbl> Ord_Tbl { get; set; }
        public virtual DbSet<Orderr> Orderrs { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProImage> ProImages { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<PRODUCT_VIEWS> PRODUCT_VIEWS { get; set; }
    
        public virtual ObjectResult<DriverOrderss_Result> DriverOrderss()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DriverOrderss_Result>("DriverOrderss");
        }
    
        public virtual ObjectResult<Drivers_Orderss_Result> Drivers_Orderss()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Drivers_Orderss_Result>("Drivers_Orderss");
        }
    
        public virtual ObjectResult<GetAllOrdersss_Result> GetAllOrdersss()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllOrdersss_Result>("GetAllOrdersss");
        }
    }
}
