//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFloristNewApp18.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ord_Tbl
    {
        public int op_id { get; set; }
        public int pro_id { get; set; }
        public int order_id { get; set; }
        public Nullable<int> quantity { get; set; }
    }
}
