//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFloristNewApp18.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orderr()
        {
            this.Drivers = new HashSet<Driver>();
        }
    
        public int ord_id { get; set; }
        public decimal totalPrice { get; set; }
        public string ord_street { get; set; }
        public string ord_city { get; set; }
        public string ord_province { get; set; }
        public string ord_country { get; set; }
        public string email { get; set; }
        public string ord_status { get; set; }
        public string ord_deliveryStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Drivers { get; set; }
        public virtual Table Table { get; set; }
    }
}
