//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFloristNewApp18.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int payment_id { get; set; }
        public string card_name { get; set; }
        public string card_CCV { get; set; }
        public string card_expMonth { get; set; }
        public string card_expYear { get; set; }
        public string pay_date { get; set; }
        public string email { get; set; }
    
        public virtual Table Table { get; set; }
    }
}
