//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFloristNewApp18.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProImage
    {
        public int img_id { get; set; }
        public byte[] Image { get; set; }
        public int prod_id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
