//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFloristNewApp18.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public int supp_id { get; set; }
        public string s_email { get; set; }
        public string s_password { get; set; }
        public string s_contact { get; set; }
    }
}
